name: Deploy para cPanel

on:
  push:
    branches:
      - main  # dispara a cada push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Enviar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /public_html/mercadopar/   # ajuste para a pasta correta
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            .env.example
